ALTER TABLE rent_users 
ADD COLUMN credit_score INT DEFAULT 0 COMMENT '芝麻信用分',
ADD COLUMN credit_free_amount DECIMAL(10,2) DEFAULT 0 COMMENT '免押金额度',
ADD COLUMN gender VARCHAR(10) DEFAULT '' COMMENT '性别',
ADD COLUMN province VARCHAR(50) DEFAULT '' COMMENT '省份',
ADD COLUMN city VARCHAR(50) DEFAULT '' COMMENT '城市',
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

CREATE INDEX idx_credit_score ON rent_users (credit_score);
