ALTER TABLE rent_users ADD COLUMN credit_score INT DEFAULT 0;
ALTER TABLE rent_users ADD COLUMN credit_free_amount DECIMAL(10,2) DEFAULT 0;
ALTER TABLE rent_users ADD COLUMN gender VARCHAR(10) DEFAULT '';
ALTER TABLE rent_users ADD COLUMN province VARCHAR(50) DEFAULT '';
ALTER TABLE rent_users ADD COLUMN city VARCHAR(50) DEFAULT '';
ALTER TABLE rent_users ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
